// Gli hotel dove il fornitore passa a prendere i clienti: 562, tutta la zona
// turistica di Tenerife, dal sud a Puerto de la Cruz.
//
// Servono a una cosa sola: far scrivere al cliente il nome giusto. "Hotel
// Colon" sono tre alberghi diversi, e l'ufficio che legge la richiesta su
// WhatsApp non puo' indovinare quale. Qui il cliente scrive tre lettere e
// sceglie da un elenco.
//
// I nomi vengono dal widget del fornitore (vedi dati-fornitore/README.md),
// riscritti in maiuscolo/minuscolo normale perche' l'originale era tutto in
// stampatello. Cinque doppioni tolti a mano dopo aver controllato che il punto
// di raccolta coincidesse: lo stesso albergo scritto in due modi.
//
// **Qui non ci sono ne' punti di raccolta ne' orari.** Il punto dipende solo
// dall'hotel e l'ora dipende dall'escursione: sono due tabelle diverse, e
// arrivano dopo. Un orario e' una promessa, e va confermato dall'ufficio prima
// di finire sotto gli occhi di un cliente.
//
// L'elenco e' in ordine alfabetico: e' l'ordine in cui il browser li mostra.

const HOTELS = [
  "ABAMA The Ritz-Carlton",
  "Acapulco",
  "Achacay",
  "Adelfas",
  "Adonis Plaza",
  "Agaves",
  "Aguamar",
  "Aguaviva",
  "Alamo Park",
  "Alondras Park",
  "Alondras Park Club (costa del Silencio)",
  "Alta Aptos",
  "Altamar",
  "Altamira",
  "Alua Atlántico Golf Resort (antiguo aguamarina)",
  "Alua Tenerife (turquesa Playa)",
  "AluaSoul Costa Adeje (Antiguo La niña)",
  "AluaSoul Orotava Valley",
  "Amarilla Bay",
  "Ambassador (club)",
  "Americas",
  "Andalucia",
  "Andorra",
  "Andreas",
  "Anica Sur",
  "Annapurna - (alborada Beach Club)",
  "Anthelia",
  "Apartamento Acantilados Gigantes",
  "APARTAMENTO JACARANDA las americas",
  "Apartamento Lago Santiago",
  "Apartamento Parque Carolina (costa del Silencio)",
  "Apartamentos Albatros (callao Salvaje)",
  "Apartamentos Aloha Garden",
  "Apartamentos Arena",
  "Apartamentos Atlantico",
  "Apartamentos Bahia",
  "Apartamentos Buenavista",
  "Apartamentos Casa Tropical",
  "Apartamentos Casablanca",
  "Apartamentos Colonial I",
  "Apartamentos Cosmopolitan Tenerife",
  "Apartamentos Costa Adeje Oasis",
  "Apartamentos Dream View",
  "Apartamentos Duque",
  "Apartamentos el Ancla",
  "Apartamentos Fañabe",
  "Apartamentos Geranios (costa del Silencio)",
  "Apartamentos Golf del Sur",
  "Apartamentos Hercules",
  "Apartamentos Jardin (los Gigantes)",
  "Apartamentos la Colina",
  "Apartamentos la Estrella",
  "Apartamentos las Vistas",
  "Apartamentos los Cristianos",
  "Apartamentos los Pueblos",
  "Apartamentos Playa la Arena",
  "Apartamentos Playa Veronicas",
  "Apartamentos Poblado Marinero",
  "Apartamentos Puerto Santiago",
  "Apartamentos San Eugenio Alto",
  "Apartamentos Siam",
  "Apartamentos Tagara Beach",
  "Apartamentos Tamay I-vii",
  "Apartamentos Teneguia",
  "Apartamentos Tenerife Best",
  "Apt Aguamarina",
  "Apt el Carmen",
  "Aptos Miramar",
  "Aquarius",
  "Arco Iris Playa",
  "Arena Suites",
  "Arenas del Mar",
  "Arenas Negras",
  "Arona Gran",
  "Astoria Hotel",
  "Atalaya Court",
  "Atlantic Holidays",
  "Atlantic Mirage Suites & SPA",
  "Atlantic Palace",
  "Atlantic View",
  "Atlantida",
  "Augusta Park",
  "Avenida Hotel",
  "Azahara",
  "Bahia Colon",
  "Bahia del Duque",
  "Bahia Fanabe Suites",
  "Bahia Flamingo",
  "Bahia Playa",
  "Bahia Principe Costa Adeje",
  "Balcon Atlantico",
  "Balcon del Mar",
  "Balcones los Gigantes",
  "Bambi Hotel",
  "Baobab Suites",
  "Barceló Santiago",
  "Barceló Tenerife (Sandos San Blas)",
  "Barranco",
  "Be Live Adults Only",
  "Be Live Experience Orotava",
  "Belair",
  "Benimar",
  "Best Tenerife",
  "Beverly Hills Club",
  "Beverly Hills High",
  "Big Sur",
  "Bitacora",
  "Blue Sea",
  "Blue Sea Costa",
  "BLUESEA Puerto Resort",
  "Borinquen",
  "Botanico",
  "Bouganville",
  "Bucanero",
  "Buenavista Gigantes",
  "Cactus",
  "Caledonia Park",
  "Callao Garden",
  "Canarife (blue Sea)",
  "Carabela",
  "Cardones",
  "Caribe",
  "Casa Bonita Aptos",
  "Casa Calma",
  "Casa del Sol Hotel",
  "Casa el Hierro",
  "Casa las Cupulas",
  "Castle Harbour",
  "Chaparral",
  "Chayofa Club",
  "Chimisay",
  "Chinyero",
  "Chipeque",
  "Cleopatra",
  "Club Atlantis",
  "Club la Mar",
  "Club la Paz",
  "Club Marino",
  "Club Olympus",
  "Club Paraiso",
  "Club Paraiso Aptos",
  "Club Tenerife",
  "Colina",
  "Colina Blanca",
  "Colon Guanahani",
  "Colon I",
  "Colon II",
  "Columbus",
  "Comodoro",
  "Concordia Hotel",
  "Conde Tio Medina",
  "Condesa",
  "Conquistador",
  "Contemporaneo",
  "Copacabana",
  "Coral California",
  "Coral Compostela Beach",
  "Coral Compostela Golf",
  "Coral Dreams",
  "Coral Ocean View",
  "Corales Suites Caleta",
  "Cortijo",
  "Costa Adeje Garden",
  "Costa Adeje Gran",
  "Costa del Silencio",
  "Costamar",
  "Cristian Mar",
  "Cristianos III",
  "Cristiansur",
  "Cruceros",
  "Cruceros Muelle",
  "Diamante Suites",
  "Diamantes",
  "Dinastia",
  "Direct Harbour",
  "Don Antonio",
  "Don Candido Hotel",
  "Don Jose",
  "Don Manolito",
  "Dorado",
  "Drago",
  "Dragos del Sur",
  "Duquesa del Mar",
  "Edf. Crisol",
  "Edificio Artista",
  "El Beril",
  "El Cardon",
  "El Duque",
  "El Mirador",
  "El Navio",
  "El Rincon",
  "El Sombrero Apt los Gigantes",
  "El Tope",
  "Esplanade Hotel",
  "Estrella",
  "Eucalipto",
  "Fairways",
  "Fantasia Bahia Principe Golf del Sur",
  "Fañabe Costa Sur",
  "Fergus P",
  "Fergus Puerto de la Cruz",
  "Flamingo Beach Mate",
  "Flores del Sol",
  "Florida",
  "Florida Park",
  "Florida Plaza Be Smart",
  "Floritas",
  "Funchal",
  "Gala",
  "Gara Suites",
  "Garajonay",
  "Garden City",
  "Garoe",
  "Germinio",
  "GF Fañabe",
  "GF Isabel",
  "GF Victoria",
  "Girasol",
  "Globales Acuario",
  "Golf Plaza",
  "Gran Callao Sport",
  "Gran Melia Palacio de Isora",
  "Gran Muthu Golf Plaza",
  "Gran Tacande",
  "Gran Tinerfe",
  "Granada Park",
  "Grand Muthu Golf Plaza",
  "Green Garden Golf Resort",
  "Green Park",
  "Green Park Golf",
  "Guajara Aptos",
  "Guayarmina",
  "Guayero",
  "H10 Atlantic Sunset",
  "H10 Costa Adeje Palace",
  "H10 Tenerife Playa",
  "Hacienda II",
  "Hapimag Hotel",
  "Hard Rock Hotel",
  "HG Tenerife Sur",
  "Hollywood Mirage",
  "Horizonte",
  "Hostal Carel",
  "Hostal Duendes del Sur",
  "Hostal Tenerife",
  "Hotel AF Valle Orotava - Puerto de la Cruz",
  "Hotel Las Águilas Tenerife, Affiliated by Meliá",
  "Hotel Medano",
  "Hotel Playa la Arena Landmar",
  "Hotel Silken Saaj Maar Puerto de la Cruz",
  "Hovima Atlantis",
  "Hovima Costa Adeje",
  "Hovima Jardin Caleta",
  "HOVIMA SUITES (Labranda Suite C. Adeje)",
  "Ikarus",
  "Interpalace (blue Sea)",
  "Island Village",
  "Jacaranda",
  "Jardin Canario",
  "Jardin Tropical",
  "Jardines del Duque",
  "Jardines del Teide",
  "Jardines Nivaria",
  "Jardines Sur",
  "Klayman Diamond Aparthotel",
  "La Ballena",
  "La Duquesa",
  "La Pinta",
  "La Plantacion del Sur",
  "La Quinta Park Coral",
  "La Siesta",
  "La Tortuga",
  "La Toscana",
  "La Vaggi",
  "Labranda bahía Fañabé",
  "Lagos de Cesar",
  "Lagos Fañabe",
  "Laguna Park I",
  "Laguna Park II",
  "Landmar Costa Los Gigantes",
  "Las Barandas",
  "Las Brisas",
  "Las Caravelas",
  "Las Dalias",
  "Las Flores",
  "Las Fuentes",
  "Las Madrigueras",
  "Las Palmeras",
  "Las Terrazas",
  "Las Vegas Hotel",
  "Las Viñas",
  "Los Alisios",
  "Los Angeles",
  "Los Arcos",
  "Los Brezos",
  "Los Cardones",
  "Los Claveles",
  "Los Geranios",
  "Los Gigantes View",
  "Los Hibiscos",
  "Los Olivos",
  "Maga",
  "Magec",
  "Magnolia Golf Resort Aptos",
  "Malibu Park",
  "Mar y Sol",
  "Maravilla",
  "Marazul Aptos",
  "Mareverde",
  "Marina Palace",
  "Marina Primavera",
  "Marina View",
  "Marola Park",
  "Marques Palace",
  "Marquesa",
  "Marte",
  "Marylanza",
  "Marysol",
  "Masaru",
  "Mediterranean",
  "Melia la Paz",
  "Meliá Hacienda del Conde (buenavista)",
  "Mencey",
  "Mirador de la Gomera",
  "Mirador del Duque Iberostar",
  "Miramar",
  "Miramar Elegance Hotel",
  "Miraverde",
  "Molino Blanco",
  "Monopol",
  "Montesol",
  "Muthu Royal Park Albatros",
  "MYND Adeje",
  "Neptuno",
  "Noelia Playa",
  "Oasis del Duque",
  "Oasis Golf",
  "Oasis Gran Resort",
  "Oasis la Caleta",
  "Oasis Paraiso",
  "Ocean Park",
  "OHASIS APARTMENTS (antigüo Oasis Mango)",
  "Ole Tropical Tenerife",
  "Olimpia",
  "Olivina",
  "Optimist",
  "Orlando",
  "Oro Blanco",
  "Oro Negro",
  "Oro Verde",
  "Palia Don Pedro",
  "Palm Beach Club",
  "Palm-mar",
  "Palmeras del Sur",
  "Palmeras Playa Hotel",
  "Palo Blanco",
  "Paloma Beach",
  "Panorama",
  "Panoramica",
  "Panoramica Heights",
  "Paradero",
  "Paradero II",
  "Paradise Court",
  "Paradise Park",
  "Paraiso del Sol",
  "Paraiso del Sol II",
  "Paraiso del Sur Aptos",
  "Paraiso Floral",
  "Paraiso Royal",
  "Paraiso Sur",
  "Paramount",
  "Parcis Roy",
  "Park Club Europe",
  "Park Plaza",
  "Parque Americas",
  "Parque Catleya",
  "Parque Cristobal",
  "Parque del Sol",
  "Parque la Paz",
  "Parque Margarita",
  "Parque Royal",
  "Parque San Eugenio",
  "Parque Santiago I",
  "Parque Santiago II",
  "Parque Santiago III",
  "Parque Santiago IV",
  "Parque Tropical",
  "Parque Vacacional Edén",
  "Parque Verde",
  "Pebble Beach",
  "Perla Gris",
  "Pez Azul",
  "Piramides",
  "Piteras",
  "Playa Azul",
  "Playa Fañabe",
  "Playa Flor",
  "Playa Graciosa",
  "Playa Honda",
  "Playa la Arena Residencial",
  "Playa Olid",
  "Playa Paraiso",
  "Playa Real",
  "Playa Sur Medano",
  "Ponderosa",
  "Port Royal",
  "Porto Nova",
  "Precise Resort Puerto (Anterior Maritim)",
  "Primavera",
  "Princesa Isora",
  "Princess Inspire Tenerife",
  "Principe Paz Htl",
  "Privado",
  "Pueblo Primavera",
  "Pueblo Torviscas",
  "Puerto Azul",
  "Puerto de la Cruz",
  "Puerto Palace Hotel",
  "Punta del Rey (las Caletillas)",
  "Quinta Park",
  "Ramada Costa Adeje (antiguo Paradise club)",
  "Regency Club Torviscas",
  "Regency Country Club",
  "Relax Home Tenerife",
  "Residencial el Camison",
  "Residencial Oasis Fañabe III",
  "Reveron Plaza",
  "RIU Arecas",
  "RIU Buenavista",
  "RIU Palace",
  "Roca Nivaria",
  "Rocamar",
  "Rocas del Mar",
  "Rock Plaza",
  "Roque del Conde",
  "Rosamar",
  "Route Active",
  "Royal Garden",
  "Royal Garden Villas",
  "Royal Hideaway Coral Suites",
  "Royal Marina Golf",
  "Royal Palm",
  "Royal River Luxury",
  "Royal Sun Hotel",
  "Royal Sun Resort",
  "Royal Sunset (gigantes)",
  "Royal Sunset Beach Club",
  "Royal TFE Country Club (san Andres)",
  "Sabila Iberostar",
  "Saint George",
  "San Felipe Hotel",
  "San Marino",
  "San Telmo",
  "San Telmo Hotel",
  "Sand Club",
  "Santa Amalia",
  "Santa Barbara Golf and Ocean Club",
  "Santa Maria",
  "Santa Monica",
  "Saphire Club",
  "Scorpio",
  "Semiramis",
  "Sendymar",
  "Servatur Isora (ex Allegro)",
  "Sholeo los Gigantes",
  "Silken Atlantida Htl",
  "Sir Anthony",
  "Sol Arena",
  "Sol Arona Tenerife by Melia",
  "Sol Atlantis Hotel",
  "Sol Costa Atlantis",
  "Sol Puerto de la Cruz Tenerife",
  "Sol Sun Beach",
  "Sol Tenerife",
  "Solmar",
  "Sueño Azul",
  "Summerland",
  "Sun Holidays",
  "Sunbay",
  "Sunprime Coral Suites & SPA",
  "Sunrises la Caleta",
  "Sunset Bay",
  "Sunset Harbour",
  "Sunset View",
  "Sunwing",
  "Sur y Sol",
  "Tajinaste",
  "Tamaimo Tropical",
  "Taoro Garden Hotel",
  "Tarajal",
  "Taucho Cottage",
  "Tegueste",
  "Teide Mar",
  "Tenerife by the Ocean Aptos",
  "Tenerife Playa Hotel",
  "Tenerife Royal Garden",
  "Tenerife Ving",
  "Terraza los Gigantes",
  "Terrazas de la Paz",
  "Terrazas del Duque",
  "The Harbour Club",
  "The Heights",
  "The Salmar (vinci Golf Ant)",
  "Tigaiga Hotel",
  "Tigotan",
  "Tiime Hart",
  "Tinerfe Garden",
  "Tivoli La Caleta (Antiguo sheraton la caleta)",
  "Torres Sol",
  "Torres Yomeli",
  "Townhouse el Duque",
  "Townhouse la Caleta",
  "Tropical Park",
  "Trovador",
  "Troya",
  "TUI Blue los Gigantes",
  "Twinfin Surf Camp",
  "Udalla Park",
  "Urbania Club",
  "Vacation Home la Duquesa",
  "Vallemar Hotel",
  "Vanilla Garden",
  "Vera Mar",
  "Veril del Duque I Aptos",
  "Veril del Duque II Aptos",
  "Victoria Court I",
  "Victoria Court II",
  "Vigilia Park",
  "Villa Adeje Beach",
  "Villa Caleta Golf",
  "Villa Cortes",
  "Villa Fañabe Suites",
  "Villa la Caleta",
  "Villa Mandi Golf Resort",
  "Villa Mar",
  "Villa Maria",
  "Villa Mojon Callao Salvaje",
  "Villa Natalie",
  "Villa Tagoro",
  "Villamar",
  "Villas Canarias",
  "Villas del Duque",
  "Villas Madro",
  "Villas Nivaria",
  "Villas San Eugenio",
  "Villas Tenerife",
  "Villas y Bahia Fañabe",
  "Villas Yucca",
  "Virginia II",
  "Vista Hermosa",
  "Vistasur",
  "Viñas del Mar",
  "Vulcano",
  "Weare la Paz",
  "West Haven Bay",
  "Winsor Park",
  "Winter Garden",
  "Wyndham Costa Adeje (Antiguo Monterey)",
  "Wyndham Golf del Sur (Antiguo Sunningdale)",
  "Xibana",
  "Yucca Park",
  "Zentral Center"
];
